// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Projet_Finale.Data;

#nullable disable

namespace Projet_Finale.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20251031124907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Projet_Finale.Model.Car", b =>
                {
                    b.Property<Guid>("Id_car")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSelling")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PreTaxPrices")
                        .HasColumnType("real");

                    b.Property<float>("PriceIncludingTax")
                        .HasColumnType("real");

                    b.Property<int>("Years")
                        .HasColumnType("integer");

                    b.Property<Guid>("id_client")
                        .HasColumnType("uuid");

                    b.HasKey("Id_car");

                    b.HasIndex("id_client");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Projet_Finale.Model.Client", b =>
                {
                    b.Property<Guid>("id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_client");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Projet_Finale.Model.Car", b =>
                {
                    b.HasOne("Projet_Finale.Model.Client", "Client")
                        .WithMany("Car")
                        .HasForeignKey("id_client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Projet_Finale.Model.Client", b =>
                {
                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
